# Generated by Django 5.1.5 on 2025-01-31 12:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_deliveredquote'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveredquote',
            options={'ordering': ['-delivery_date', 'delivery_order']},
        ),
        migrations.RemoveIndex(
            model_name='deliveredquote',
            name='api_deliver_deliver_26bf1f_idx',
        ),
        migrations.RemoveIndex(
            model_name='deliveredquote',
            name='api_deliver_quote_i_956fa8_idx',
        ),
        migrations.AlterUniqueTogether(
            name='deliveredquote',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='deliveredquote',
            name='delivery_order',
            field=models.SmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], default=1),
        ),
        migrations.AlterField(
            model_name='deliveredquote',
            name='delivery_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddConstraint(
            model_name='deliveredquote',
            constraint=models.UniqueConstraint(fields=('quote', 'delivery_date'), name='unique_quote_per_day'),
        ),
        migrations.AddConstraint(
            model_name='deliveredquote',
            constraint=models.UniqueConstraint(fields=('delivery_date', 'delivery_order'), name='unique_order_per_day'),
        ),
    ]
