# Generated by Django 5.1.5 on 2025-01-31 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_deliveredquote_delivery_order'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='deliveredquote',
            name='unique_order_per_day',
        ),
    ]
