# Generated by Django 5.1.5 on 2025-02-01 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumuser',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
