# Generated by Django 5.1.5 on 2025-02-04 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_premiumuser_is_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumuser',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='premiumuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='premiumuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
