# Generated by Django 5.1.5 on 2025-02-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_premiumuser_name_alter_premiumuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premiumuser',
            name='profile_picture',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
